version: "2.3"
services:

  xserver:
    image: devrt/xserver
    container_name: xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    ports:
      - "3000:80"

  pepperhri:
    image: pepper-hri
    container_name: pepperhri
    tty: true
    ipc: host
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    volumes_from:
      - xserver
    depends_on:
      - xserver
    volumes:
      - ${HOME}/playground:/home/robot/playground
      - $HOME/src/Pepper/pepper_tools:/home/robot/src/pepper_tools
    working_dir: /home/robot/
    entrypoint:
    - bash
    - -ci 
    - "cd /home/robot/ && ./init.bash"



